"""
Django settings for site1 project.

Generated by 'django-admin startproject' using Django 3.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a6_!=5=2v1)b#e2xv0@=6&r-pmtsl0x^_q2-z0#h-3683ta0jo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'esadbsrv',
    'albumstore',
    'docstore',
    'einst',
    'org',
    'contact',
    'channel',
    'project',
    'ttnexample',
    'meter',
    'commdevice',
    'mic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'docstore.middleware.ds_middleware',
    'albumstore.middleware.as_middleware',
    'esadbsrv.middleware.middleware',
    'org.middleware.middleware',
    'einst.middleware.middleware',
    'contact.middleware.middleware',
    'channel.middleware.middleware',
]

ROOT_URLCONF = 'esadb.urls'

TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            TEMPLATE_DIR,
            os.path.join(BASE_DIR, 'contact/templates'),
            os.path.join(BASE_DIR, 'channel/templates'),
            os.path.join(BASE_DIR, 'docstore/templates'),
            os.path.join(BASE_DIR, 'org/templates'),
            os.path.join(BASE_DIR, 'albumstore/templates'),
            os.path.join(BASE_DIR, 'project/templates'),
            os.path.join(BASE_DIR, 'ttnexample/templates'),
            os.path.join(BASE_DIR, 'meter/templates'),
            os.path.join(BASE_DIR, 'commdevice/templates'),
            os.path.join(BASE_DIR, 'mic/templates'),
            os.path.join(BASE_DIR, 'gdiskstorage/templates'),
            os.path.join(BASE_DIR, 'esadbsrv/templates'),
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'esadbsrv.context_processors.contextinfo',
                'project.context_processors.projectcontext',
                'einst.context_processors.einstcontext',
            ],
        },
    },
]

WSGI_APPLICATION = 'esadb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'cz32770_esadb',
        'USER': 'cz32770_esadb',
        'PASSWORD': 'Immelstorn',
        'OPTIONS': {
            'sql_mode': 'STRICT_TRANS_TABLES',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/home/c/cz32770/django_seofn/public_html/static'

STATICFILES_DIRS = [
   os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = '/home/c/cz32770/django_seofn/public_html/media'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
